# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'redactor.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Redactor(object):
    def __init__(self):
        self.max_answers = 5

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(575, 583)
        Form.setWindowIcon(QtGui.QIcon("handler/tester.png"))
        Form.setWindowModality(QtCore.Qt.NonModal)
        self.lineEdit = QtWidgets.QComboBox(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 531, 20))
        self.lineEdit.setEditable(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 0, 191, 31))
        self.label.setStyleSheet("font: 75 11pt \"Palatino Linotype\";")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QComboBox(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 90, 531, 51))
        self.lineEdit_2.setObjectName("textEdit")
        self.lineEdit_2.setEditable(True)
        self.upload_image = QtWidgets.QPushButton(Form)
        self.upload_image.setGeometry(QtCore.QRect(20, 150, 200, 20))
        self.upload_image.setText("Загрузить изображение")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 171, 21))
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 170, 531, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 530, 171, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.answers_line_edit = {}
        self.answers_check_box = {}
        _translate = QtCore.QCoreApplication.translate
        for i in range(self.max_answers):
            self.answers_line_edit[i] = QtWidgets.QLineEdit(self.gridLayoutWidget)
            self.answers_line_edit[i].setObjectName("lineEdit" + str(i))
            self.answers_check_box[i] = QtWidgets.QCheckBox(self.gridLayoutWidget)
            self.answers_check_box[i].setObjectName("checkBox" + str(i))
            self.gridLayout.addWidget(self.answers_check_box[i], i, 1, 1, 1)
            self.gridLayout.addWidget(self.answers_line_edit[i], i, 0, 1, 1)
            self.answers_check_box[i].setText(_translate("Form", ""))


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактор тестов"))
        self.label.setText(_translate("Form", "Название теста:"))
        self.label_2.setText(_translate("Form", "Вопрос"))
        self.pushButton_3.setText(_translate("Form", "Сохранить"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Введите вопрос или имя изображения в папке Photo"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Введите имя теста"))
