# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tester.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# import db_test_handler


class Ui_Tester(object):
    def __init__(self):
        self.max_answers = 5

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowIcon(QtGui.QIcon("tester.png"))
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.resize(788, 589)
        mainWindow.setMinimumSize(QtCore.QSize(788, 589))
        mainWindow.setMaximumSize(QtCore.QSize(788, 589))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 60, 651, 20))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 441, 20))
        self.label.setStyleSheet("font: 14pt \"Vijaya\";")
        self.label.setObjectName("label")
        self.Vibor = QtWidgets.QPushButton(self.centralwidget)
        self.Vibor.setGeometry(QtCore.QRect(680, 60, 91, 21))
        self.Vibor.setObjectName("pushButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 500, 751, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Predidush = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Predidush.setObjectName("Predidush")
        self.horizontalLayout.addWidget(self.Predidush)
        self.Sleduch = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Sleduch.setObjectName("Sleduch")
        self.horizontalLayout.addWidget(self.Sleduch)
        self.Zaverchit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Zaverchit.setObjectName("Zaverchit")
        self.horizontalLayout.addWidget(self.Zaverchit)
        self.QuestLabel = QtWidgets.QTextBrowser(self.centralwidget)
        self.QuestLabel.setGeometry(QtCore.QRect(20, 90, 751, 61))
        self.QuestLabel.setObjectName("QuestLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 159, 751, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.radioButtons = {}
        for i in range(self.max_answers):
            self.radioButtons[i] = QtWidgets.QRadioButton(self.verticalLayoutWidget)
            self.radioButtons[i].setObjectName("radioButton" + str(i))
            self.verticalLayout.addWidget(self.radioButtons[i])
            self.radioButtons[i].setText("RB" + str(i))
            _translate = QtCore.QCoreApplication.translate
            self.radioButtons[i].setText(_translate("mainWindow", "RadioButton\n"
                                                                "1\n"
                                                                "2\n"
                                                                "3"))
            self.radioButtons[i].setVisible(False)



        # mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 18))
        self.menubar.setObjectName("menubar")
        # mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        # mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Тестер"))
        self.label.setText(_translate("mainWindow", "Выберите тест:"))
        self.Vibor.setText(_translate("mainWindow", "Выбрать"))
        self.Predidush.setText(_translate("mainWindow", "Предыдущий вопрос"))
        self.Sleduch.setText(_translate("mainWindow", "Следующий вопрос"))
        self.Zaverchit.setText(_translate("mainWindow", "Завершить"))
        self.QuestLabel.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Вопрос</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5</p></body></html>"))

        self.QuestLabel.setReadOnly(True)
        self.QuestLabel.setVisible(False)
        self.Predidush.setVisible(False)
        self.Sleduch.setVisible(False)
        self.Zaverchit.setVisible(False)