# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tester.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import db_test_handler


class Ui_Tester(object):
    def setupUi(self, Tester):
        Tester.setObjectName("mainWindow")
        Tester.setWindowIcon(QtGui.QIcon("tester.png"))
        Tester.setWindowModality(QtCore.Qt.NonModal)
        Tester.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Tester)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 80, 471, 20))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 441, 20))
        self.label.setStyleSheet("font: 14pt \"Vijaya\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(530, 80, 221, 21))
        self.pushButton.setObjectName("pushButton")
        # mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Tester)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        # mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Tester)
        self.statusbar.setObjectName("statusbar")
        # Tester.setStatusBar(self.statusbar)

        self.retranslateUi(Tester)
        QtCore.QMetaObject.connectSlotsByName(Tester)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Тестер"))
        result = db_test_handler.get_tests()
        for i in range(len(result)):
            self.comboBox.addItem("")
            self.comboBox.setItemText(i, _translate("mainWindow", result[i][1]))
        # self.comboBox.setItemText(1, _translate("mainWindow", "Тест_2"))
        self.label.setText(_translate("mainWindow", "Выберите тест:"))
        self.pushButton.setText(_translate("mainWindow", "Выбрать"))
